### ISSUE TITLE
[FEATURE] Add Tabs to the Query Results Pane

### ISSUE THREAD

**Issue by jeffreyaven** [stackql/stackql-playground#30]
**Feature Description**
Add 3 tabs to the Results pane using the [MaterialUI Tab Component](https://mui.com/material-ui/react-tabs/#basic-tabs).  

Tabs:  
- **Results** (default used to return query result sets for **query** operations using `DataGridPro `and text for **get types operations**)
- **JSON** (only when queries are run, returns the result set data stringified JSON in the tab pane)
- **Execution** Details (only when queries are run, returns the metadata returned from the operation - `elapsedTime`, `rowsReturned `etc)

An example video is available [here](https://drive.google.com/file/d/1qspAm54zs95L4h1JtzZap9pD1DEwWTO2/view?usp=sharing)

**Comment by yunchengyang515** [comment]
- [x] 1. Add the tabs
- [x] 2. override the styling
- [x] 3. Add JSON tab with code editor and json result
- [x] 4. Add Execution details with code editor and metadata, make sure showMetaData is added
- [x] 5. Clean up disable behaviour https://mui.com/material-ui/react-tabs/#experimental-api
