### ISSUE TITLE
[FEATURE] Support draggable resizing for explorer, query and results panes

### ISSUE THREAD

**Issue by jeffreyaven** [stackql/stackql-playground#31]
**Feature Description**

1. Allow the **explorer pane** to be resized _horizontally_ with a control on the right hand border of the `div`
2. Allow the **query and results panes** to be resized _vertically_ with a control on the border between the two `div `s

A video demo is included [here](https://drive.google.com/file/d/1ofWrO8ANxVnrDkPSDUVQWllgiIFWML0h/view?usp=sharing)

**Comment by yunchengyang515** [comment]
Use ReactResizeable Box https://codesandbox.io/s/zl8u4?file=/src/ResizableBox.js 
1. Make sure the inner elements are only using percentage dimension
