### ISSUE TITLE
[FEATURE] Show fields and method views in the explorer pane

### ISSUE THREAD

**Issue by jeffreyaven** [stackql/stackql-playground#32]
**Feature Description**
- Show the fields under a resource using the `/providers/<providerName>/services/<serviceName>/resources/<resourceName>` api
- Show the methods under a resource using the `/providers/<providerName>/services/<serviceName>/resources/<resourceName>/methods` api

for example...

```
aws/
├─ ec2/
│  ├─ fields/
│  │  ├─ id
│  │  ├─ name
│  │  ├─ etc...
│  ├─ methods/
│  │  ├─ start
│  │  ├─ stop
│  │  ├─ etc...

```

**Comment by yunchengyang515** [comment]
1. Find the endpoints
2. Expand when clicking resource
3. need to change the lowest level that we call fetch explorer endpoint
