### ISSUE TITLE
[FEATURE] Add Save Results button for saving query results

### ISSUE THREAD

**Issue by jeffreyaven** [stackql/stackql-playground#33]
**Feature Description**
Add a button on the Results header (right justified) called **Save Results**  

This button should be a drop down with options to:  

- Save Results as CSV
- Save Results as JSON

The button is only enabled when a query is run and there are results in the **Results** pane, otherwise it is disabled

An example video is available [here](https://drive.google.com/file/d/1a_rxlpUK_2rNqT6swBEnTvLCPjhONTTY/view?usp=sharing)

**Comment by yunchengyang515** [comment]
- [x] Dropdown with button
- [ ] OnClick saveCsv
- [ ] OnClick save JSON

**Comment by yunchengyang515** [comment]
https://stackoverflow.com/questions/48760815/export-to-csv-button-in-react-table
