### ISSUE TITLE
[FEATURE] Design responsive layout to the Explorer app

### ISSUE THREAD

**Issue by jeffreyaven** [stackql/stackql-playground#34]
**Feature Description**
Design different layouts and breakpoints to make the app more responsive (although the intent it to use this on a `MD `or larger viewport)

**Comment by yunchengyang515** [comment]
### Header
- [x] Button only display icon in smaller size
- [x] Reorganising with grid
- [x] Only display power on
- [x] left two button too close to each other
<img width="488" alt="image" src="https://user-images.githubusercontent.com/45674168/200152111-98131e64-50b6-42b1-9da7-7d4fbfa97768.png">

- [x] weird outline behaviour 

<img width="453" alt="image" src="https://user-images.githubusercontent.com/45674168/200152130-0a4e125c-0b00-4d75-ac52-dc0f5a29cd7f.png">

- [x] Render icon button instead when in tablet or mobile
- [ ] Connect to server button adjustment when in laptop

![Image](https://user-images.githubusercontent.com/45674168/200199042-581ad79c-20ef-43f5-86d2-7d1f6e65d361.png)





### Pane
- [ ] Make explorer a top drawer in mobile https://www.npmjs.com/package/react-collapsible

### General

- [ ] clean up the code of icon button and button, make it a single component
