### ISSUE TITLE
[FEATURE] Copy Controls

### ISSUE THREAD

**Issue by jeffreyaven** [stackql/stackql-playground#37]
**Feature Description**
- Put a copy control in the upper right hand corner of the Query pane to copy the contents of the Query pane (the query) to the clipboard
- Put a copy control in the upper right hand corner of the Results pane, if...
Get Types is invoked (to copy the type definitions to the clipboard); or
The JSON tab is active (to copy the pretty printed JSON query results to the clipboard)

Use the [MUI `ContentCopy` Icon](https://mui.com/material-ui/material-icons/?query=copy&selected=ContentCopy) button

```javascript
import ContentCopyIcon from '@mui/icons-material/ContentCopy';
```

**Comment by yunchengyang515** [comment]
- [x] add the button to query pane
- [x] Add copy to clipboard capability
- [x] add button to result pane
- [x] Only render the button when it is getText and is results tab
