### ISSUE TITLE
[FEATURE] Click on JSON field shows modal dialog with the pretty printed JSON object

### ISSUE THREAD

**Issue by jeffreyaven** [stackql/stackql-playground#38]
**Feature Description**
When a cell in the DataGrid results pane contains JSON is clicked (left clicked) the contents should be pretty printed in a modal dialog.  

When the cell is clicked run `JSON.parse()` to ensure it is a valid JSON object, do this in a `try  catch` block if there is an error don't show the modal dialog (as it is not a valid JSON object).  The following code could be run when a cell is clicked (calling a function named `showModalDialog `to show the dialog) - use the [MUI Dialog Component](https://mui.com/material-ui/react-dialog/#customization) with  copy control in the upper right hand corner to copy the contents of the dialog (the JSON) to the clipboard and a close option:  

```typescript
function cellCicked(cellContents: any): void {
    try {
        // its an object
        showModalDialog(JSON.stringify(JSON.parse(cellContents), null, 2));
    } catch (error) {
        // its not an object
        return;
    }
}

```

Similar behaviour to the Snowflake query console as shown here:   

![click-on-results-column-which-is-an-object](https://user-images.githubusercontent.com/5146499/196857811-9dd3a889-2f11-48da-810d-e8a605c64c97.png)

**Comment by yunchengyang515** [comment]
- [x] implement cell on click
- [x] implement the modal opening

**Comment by yunchengyang515** [comment]
https://www.loom.com/share/6dbb786c75e642308ed3b0f76257d0a2
