### ISSUE TITLE
[FEATURE] Add ability to set or modify the middleware server address

### ISSUE THREAD

**Issue by jeffreyaven** [stackql/stackql-playground#43]
**Feature Description**
Includes a button in the top right hand corner of the UI (before the GitHub icon), called **Connect to StackQL Server**  

This button would display a modal form dialog where the user would put in an address (in the form of `http{s}://hostname{:port}` )  this will update the client side NextJS variables (`middlewareScheme`, `middlewareHost`, `middlewarePort`):  

```javascript
module.exports = removeImports({
  publicRuntimeConfig: {
    middlewareScheme: process.env.MIDDLEWARE_SCHEME || "http",
    middlewareHost: process.env.MIDDLEWARE_HOST || "localhost",
    middlewarePort: process.env.MIDDLEWARE_PORT || "8080",
  },
  experimental: { esmExternals: true },
  ...nextConfig
});
```
Should use a function like validate the input and error if it is incorrect:  

```javascript
function validateAddress(string) {
  let url;
  try {
    url = new URL(string);
  } catch (_) {
    return false;
    // make outline for textfield red and change the label to Invalid Address
  }
  return { middlewareScheme:  url.protocol, middlewareHost: url.hostname, middlewarePort: url.port} ;
}
```
Should use material UI components for example:  
[Code Sandbox](https://codesandbox.io/s/material-demo-forked-6il0ze?file=/demo.js)

**BONUS:**  

If the button can be context aware e.g.  
- if values for the variables are set then the button would have an end icon of `import PowerIcon from '@mui/icons-material/Power';`
- if the values for the variables are not set then the button would have an end icon of `import PowerOffIcon from '@mui/icons-material/PowerOff';`

**Comment by yunchengyang515** [comment]
- [x] Create the button component
- [x] Create simple dialog
- [x] Pass the URL as a param in the request
- [x] In API, change the middleware URL if there is URL in request param
